import {
  Award,
  CalendarDays,
  CircuitBoard,
  Copy,
  FileText,
  LifeBuoy,
  LocateFixed,
  Mail,
  Map,
  MessageSquare,
  MonitorDot,
  PackagePlus,
  PictureInPicture2,
  PieChart,
  RadioTower,
  ScrollText,
  Share2,
  ShoppingBag,
  Table,
  Trophy,
  School,
  UserRound,
  FileLineChart,
} from "lucide-react";

const menuData: any = [
  {
    label: "menu",
    isTitle: true,
  },
  {
    id: "dashboard",
    label: "Dashboards",
    link: "/#",
    icon: <MonitorDot />,
    subItems: [
      {
        id: "ecommercedashboard",
        label: "Summary Barang",
        link: "/dashboard",
        parentId: "dashboard",
      },
    ],
  },
  {
    label: "Data Master",
    isTitle: true,
  },
  {
    id: "Data User",
    label: "Data User",
    icon: <UserRound />,
    link: "/user",
  },
  {
    id: "Category",
    label: "Category",
    icon: <Copy />,
    link: "/category",
  },
  {
    id: "Kondisi",
    label: "Kondisi",
    icon: <MonitorDot />,
    link: "/kondisi",
  },
  {
    id: "Ruangan",
    label: "Ruangan",
    icon: <School />,
    link: "/ruangan",
  },
  {
    label: "Data Barang",
    isTitle: true,
  },
  {
    id: "Barang Masuk",
    label: "Barang Masuk",
    icon: <PackagePlus />,
    link: "/barang-masuk",
  },
  {
    id: "Barang Keluar",
    label: "Barang Keluar",
    icon: <PackagePlus />,
    link: "/barang-keluar",
  },
  {
    label: "Data Lainnya",
    isTitle: true,
  },
  {
    id: "Permintaan Baran",
    label: "Permintaan Barang",
    icon: <Share2 />,
    link: "/permintaan-barang",
  },
  {
    id: "Pengajuan Perbaikan",
    label: "Pengajuan Perbaikan",
    icon: <Award />,
    link: "/pengajuan-perbaikan",
  },
  {
    label: "Laporan",
    isTitle: true,
  },
  {
    id: "Laporan Barang Masuk",
    label: "Barang Masuk",
    icon: <FileLineChart />,
    link: "/laporan-barang-masuk",
  },
  {
    id: "Laporan Barang Keluar",
    label: "Barang Keluar",
    icon: <FileLineChart />,
    link: "/laporan-barang-keluar",
  },
  {
    id: "Laporan Permintaan Barang",
    label: "Permintaan Barang",
    icon: <FileLineChart />,
    link: "/laporan-permintaan-barang",
  },
  {
    id: "Laporan Pengajuan Perbaikan",
    label: "Pengajuan Perbaikan",
    icon: <FileLineChart />,
    link: "/laporan-pengajuan-perbaikan",
  },
  {
    id: "Laporan Barang Habis",
    label: "Barang Habis",
    icon: <FileLineChart />,
    link: "/laporan-barang-rusak",
  },
  {
    id: "Laporan Barang Rusak",
    label: "Barang Rusak",
    icon: <FileLineChart />,
    link: "/laporan-barang-rusak",
  },
  {
    id: "Laporan Barang Hilang",
    label: "Barang Hilang",
    icon: <FileLineChart />,
    link: "/laporan-barang-hilang",
  },
  {
    id: "Laporan Barang Service",
    label: "Barang Service",
    icon: <FileLineChart />,
    link: "/laporan-barang-service",
  },
];

export { menuData };
